apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: low
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: low
  namespace: production
subjects:
- kind: Group
  name: jr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: low 
  apiGroup: rbac.authorization.k8s.io