apiVersion: v1
kind: Secret
metadata:
  name: mysql-test-secret
  namespace: test
  labels:
    tier: test
    app: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cHJvamVjdEFiMTIzNA==
  MYSQL_DATABASE: cHJvamVjdF9rOHM=
  MYSQL_USER: emFicmE=
  MYSQL_PASSWORD: cHJvamVjdDEyMzQ=