apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: all
  name: low-cluster-wide
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: low-cluster-wide-b
  namespace: all
subjects:
- kind: Group
  name: sr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: low-cluster-wide
  apiGroup: rbac.authorization.k8s.io